global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['otelcol:8888']
      - targets: ['otelcol:8889']
